<?php

use Drupal\custom_jmeter_boot_manager\Service\JmeterBootManagerService;

/**
 * Implements hook_cron().
 */
function custom_jmeter_boot_manager_cron() {
  $message_string = '';
  foreach (JmeterBootManagerService::getServers() as $jmeter) {
    $message_string = JmeterBootManagerService::actionExists($jmeter) ?: '';
    if ($message_string === '') continue;
    if (JmeterBootManagerService::downTimeFlag($jmeter)) {
      JmeterBootManagerService::deleteAction($jmeter);
    }
  }
}
