<?php

// use Drupal\custom_jmeter_boot_manager\Form\JmeterBootManagerForm;

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\custom_jmeter_boot_manager\Service\JmeterBootManagerService;

/**
 * Implements hook_cron().
 */
function custom_jmeter_boot_manager_cron() {
  $message_string = '';
  foreach (JmeterBootManagerService::getServers() as $jmeter) {
    $message_string = JmeterBootManagerService::actionExists($jmeter) ?: '';
    if ($message_string === '') continue;
    $create_time = JmeterBootManagerService::getActionCreate($jmeter);
    $create_time = (new DateTime())->setTimestamp($create_time);
    $datetime = new DrupalDateTime('now');
    $diff = $datetime->diff($create_time);
    if ($diff->h >= JmeterBootManagerService::SERVER_SHUTDOWN_TIME) {
      JmeterBootManagerService::deleteAction($jmeter);
    }
  }
}

/**
* Implements hook_preprocess_HOOK().
*/

function custom_jmeter_boot_manager_preprocess_html(&$variables) {
  $message_string = '';
  foreach (JmeterBootManagerService::getServers() as $jmeter) {
    $message_string = JmeterBootManagerService::actionExists($jmeter) ?: '';
    if ($message_string === '') continue;
    $create_time = JmeterBootManagerService::getActionCreate($jmeter);
    $create_time = (new DateTime())->setTimestamp($create_time);
    kint($create_time);
    exit;
    $datetime = new DrupalDateTime('now');
    $diff = $datetime->diff($create_time);
    if ($diff->h >= JmeterBootManagerService::SERVER_SHUTDOWN_TIME) {
      JmeterBootManagerService::deleteAction($jmeter);
    }
  }
}
