name: sandbox
recipe: drupal10
config:
  php: "8.1"
  via: apache:2.4
  webroot: web
keys: true
services:
  appserver:
    ssl: true
    config:
      php: .vscode/php.ini
  phpmyadmin:
    ssl: true
    type: phpmyadmin
    app_mount: false
