<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
* Implements hook_entity_insert().
*/

function custom_save_without_page_redirect_entity_insert(EntityInterface $entity) {
  if (!$entity instanceof NodeInterface) return;
  $redirect_path = '/';
  $redirect_url = Url::fromUserInput($redirect_path)->toString();
  $redirect_response = new RedirectResponse($redirect_url);
  kint($redirect_response);
  $redirect_response->send();
}

/**
* Implements hook_entity_update().
*/

function custom_save_without_page_redirect_entity_update(EntityInterface $entity) {
  custom_save_without_page_redirect_entity_insert($entity);
}
